const ordrDats = {
  "id":"4TH197952P9495535",
  "status":"COMPLETED",
  "payment_source":{
    "card":{
      "last_digits":"0270",
      "brand":"VISA",
      "type":"CREDIT"
    }
  },
  "purchase_units":[
    {
      "reference_id":"default",
      "payments":{
        "captures":[
          {
            "id":"91U85134WG748204F",
            "status":"COMPLETED",
            "amount":{
              "currency_code":"EUR",
              "value":"55.00"
            },
            "final_capture":true,
            "seller_protection":{
              "status":"NOT_ELIGIBLE"
            },
            "seller_receivable_breakdown":{
              "gross_amount":{
                "currency_code":"EUR",
                "value":"55.00"},
                "paypal_fee":{
                  "currency_code":"EUR",
                  "value":"2.12"
                },
                "net_amount":{
                  "currency_code":"EUR",
                  "value":"52.88"
                }
              },
              "links":[
                {
                  "href":"https://api.sandbox.paypal.com/v2/payments/captures/91U85134WG748204F","rel":"self",
                  "method":"GET"
                },
                {
                  "href":"https://api.sandbox.paypal.com/v2/payments/captures/91U85134WG748204F/refund",
                  "rel":"refund",
                  "method":"POST"
                },
                {"href":"https://api.sandbox.paypal.com/v2/checkout/orders/4TH197952P9495535","rel":"up",
                "method":"GET"
              }
            ],
            "create_time":"2022-12-24T14:38:04Z",
            "update_time":"2022-12-24T14:38:04Z",
            "processor_response":{
              "avs_code":"Y",
              "cvv_code":"M",
              "response_code":"0000"
            }
          }
        ]
      }
    }
  ],
  "links":[
    {
      "href":"https://api.sandbox.paypal.com/v2/checkout/orders/4TH197952P9495535",
      "rel":"self",
      "method":"GET"
    }
  ]
  }